Libraries

In [140]:
import pandas as pd

Loading the main dataset of stop times & info

In [141]:
transitdf = pd.read_csv('data/stop_times.txt')
transitdf.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled,timepoint
0,14827490,5:10:00,5:10:00,646,1,NaN,0,0,NaN,1
1,14827490,5:17:53,5:17:53,1277,10,NaN,0,0,3.4113,0
2,14827490,5:18:49,5:18:49,1279,11,NaN,0,0,3.8104,0
3,14827490,5:20:07,5:20:07,56,12,NaN,0,0,4.3660,0
4,14827490,5:20:41,5:20:41,12619,13,NaN,0,0,4.6101,0

In [142]:
transitdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 1833817 entries, 0 to 1833816
Data columns (total 10 columns):
 #   Column               Dtype
---  ------               -----
 0   trip_id              int64
 1   arrival_time         str
 2   departure_time       str
 3   stop_id              int64
 4   stop_sequence        int64
 5   stop_headsign        float64
 6   pickup_type          int64
 7   drop_off_type        int64
 8   shape_dist_traveled  float64
 9   timepoint            int64
dtypes: float64(2), int64(6), str(2)
memory usage: 139.9 MB

In [143]:
transitdf = transitdf[['trip_id', 'arrival_time', 'stop_id']]
transitdf.head()

    trip_id arrival_time  stop_id
0  14827490      5:10:00      646
1  14827490      5:17:53     1277
2  14827490      5:18:49     1279
3  14827490      5:20:07       56
4  14827490      5:20:41    12619

Filtering for route name and stop code using trips & stops dataset

In [144]:
tripsdf = pd.read_csv('data/trips.txt')
tripnamesdf = tripsdf[['trip_id', 'trip_headsign']]
tripnamesdf.head()

    trip_id                   trip_headsign
0  14827490  2 Macdonald/To Burrard Station
1  14827491  2 Macdonald/To Burrard Station
2  14827492  2 Macdonald/To Burrard Station
3  14827493  2 Macdonald/To Burrard Station
4  14827494  2 Macdonald/To Burrard Station

In [145]:
stopsdf = pd.read_csv("data/stops.txt")
stopsdf = stopsdf[['stop_id', 'stop_code']]
stopsdf['stop_id'] = pd.to_numeric(stopsdf['stop_id'], downcast='integer', errors='coerce')
stopsdf.head()

   stop_id  stop_code
0      1.0    50001.0
1  10000.0    59326.0
2  10001.0    59324.0
3  10002.0    59323.0
4  10003.0    59325.0

Joining tables to filter for 99-B line

In [146]:
transitdf = pd.merge(transitdf, tripnamesdf, on=['trip_id'])
transitdf = pd.merge(transitdf, stopsdf, on=['stop_id'])
transitdf.head(10)

    trip_id arrival_time  stop_id                   trip_headsign  stop_code
0  14827490      5:10:00      646  2 Macdonald/To Burrard Station    50640.0
1  14827490      5:17:53     1277  2 Macdonald/To Burrard Station    51267.0
2  14827490      5:18:49     1279  2 Macdonald/To Burrard Station    51269.0
3  14827490      5:20:07       56  2 Macdonald/To Burrard Station    50056.0
4  14827490      5:20:41    12619  2 Macdonald/To Burrard Station    60359.0
5  14827490      5:21:03       58  2 Macdonald/To Burrard Station    50058.0
6  14827490      5:21:29       59  2 Macdonald/To Burrard Station    50059.0
7  14827490      5:22:09       61  2 Macdonald/To Burrard Station    50061.0
8  14827490      5:22:49       63  2 Macdonald/To Burrard Station    50063.0
9  14827490      5:23:16       64  2 Macdonald/To Burrard Station    50064.0

In [147]:
blinedf = transitdf[(transitdf['trip_headsign'] == "99 Broadway B-Line/To Commercial-Broadway Station")]
blinedf.head()

,trip_id,arrival_time,stop_id,trip_headsign,stop_code
1565014,14898005,8:16:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
1565015,14898005,8:50:38,887,99 Broadway B-Line/To Commercial-Broadway Station,50880.0
1565016,14898005,8:54:30,10620,99 Broadway B-Line/To Commercial-Broadway Station,58614.0
1565017,14898005,8:58:36,9051,99 Broadway B-Line/To Commercial-Broadway Station,58499.0
1565018,14898005,9:01:18,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0

Obtaining first & last stops and elapsed times

In [148]:
blinedf = blinedf[(blinedf['stop_code'] == 58491.0) | (blinedf['stop_code'] == 61935.0)]
blinedf.sort_values(by=['trip_id'])
blinedf

,trip_id,arrival_time,stop_id,trip_headsign,stop_code
1565014,14898005,8:16:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
1565018,14898005,9:01:18,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0
1565028,14898006,8:19:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
1565032,14898006,9:04:18,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0
1565042,14898007,8:22:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
...,...,...,...,...,...
1577848,14900040,24:58:27,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0
1577858,14900041,24:41:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
1577862,14900041,25:13:27,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0
1577872,14900042,25:05:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0
1577876,14900042,25:36:30,8916,99 Broadway B-Line/To Commercial-Broadway Station,58491.0

In [149]:
blinedf['arrival_time'] = pd.to_datetime(blinedf['arrival_time'], format= '%H:%M:%S', errors = 'coerce')
blinedf['ending_time'] = blinedf.groupby('trip_id')['arrival_time'].shift(-1)
blinedf['delta_time'] = (blinedf['ending_time'] - blinedf['arrival_time'])
blinedf = blinedf[pd.notnull(blinedf['delta_time'])]
blinedf.head()

,trip_id,arrival_time,stop_id,trip_headsign,stop_code,ending_time,delta_time
1565014,14898005,1900-01-01 08:16:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0,1900-01-01 09:01:18,0 days 00:45:18
1565028,14898006,1900-01-01 08:19:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0,1900-01-01 09:04:18,0 days 00:45:18
1565042,14898007,1900-01-01 08:22:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0,1900-01-01 09:07:18,0 days 00:45:18
1565056,14898008,1900-01-01 08:25:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0,1900-01-01 09:10:18,0 days 00:45:18
1565070,14898009,1900-01-01 08:28:00,12057,99 Broadway B-Line/To Commercial-Broadway Station,61935.0,1900-01-01 09:13:18,0 days 00:45:18

New dataframe with cleaned values

In [161]:
bline_to_commercial = blinedf.reset_index()
bline_to_commercial = bline_to_commercial[['arrival_time', 'ending_time', 'delta_time']]
bline_to_commercial['delta_time_min'] = bline_to_commercial['delta_time'].dt.total_seconds().div(60)
bline_to_commercial

           arrival_time         ending_time      delta_time  delta_time_min
0   1900-01-01 08:16:00 1900-01-01 09:01:18 0 days 00:45:18            45.3
1   1900-01-01 08:19:00 1900-01-01 09:04:18 0 days 00:45:18            45.3
2   1900-01-01 08:22:00 1900-01-01 09:07:18 0 days 00:45:18            45.3
3   1900-01-01 08:25:00 1900-01-01 09:10:18 0 days 00:45:18            45.3
4   1900-01-01 08:28:00 1900-01-01 09:13:18 0 days 00:45:18            45.3
..                  ...                 ...             ...             ...
363 1900-01-01 22:12:00 1900-01-01 22:48:24 0 days 00:36:24            36.4
364 1900-01-01 22:27:00 1900-01-01 23:03:24 0 days 00:36:24            36.4
365 1900-01-01 22:42:00 1900-01-01 23:18:24 0 days 00:36:24            36.4
366 1900-01-01 22:57:00 1900-01-01 23:33:24 0 days 00:36:24            36.4
367 1900-01-01 23:12:00 1900-01-01 23:47:24 0 days 00:35:24            35.4

[368 rows x 4 columns]